apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgAixVX7KdNvG9KHhrZEBFPTudkzuGc9OK6C54e6eE726pQ/+Ui704KBBSIbZKo2Qs27xxrMp7xA4gWSQuKYyLHoBUCUpJYb+OOvfjw37/nzRv2yLtk9LZsiPAVKLYY66ueYk6au1dk/drcNLQlTcWZwMDrSjsArpI/3T2YyF378eBvoI2G7eOJ86AIymn12FNnq7zBeR3mNMuZihf9cxj1TQgF4MtZ2AKzMhhAXTBTOhtbwscAg8EM2VHlt2ZTv4jik4fP2yGj5JvH63AYDkf6PkWdVirs1qLenekiHb6ALCJfDOAKQH8lBJWrvX6PxvKsbgFoN41lr6OLd6H7H6NzVgI1PEOABReDw6xqwBq/7PrSO7lG/g9xiTucMSepL54v4kZe1EJHJ5vi/8XClX3EmT3Ov7VGotP3JgDTGnnxM5zw6Xve0Uyk/U7SWzCQRMbaT7T9WkTqsRSlIj5SRjc5dEJh+s3kjRE/UHognivcBXKb/Z+k0uGaOrLuJuYfQx0S20Sa8a1SZRnHDrZDyjP/j/WcsLvl0Wb/XdfcQ0UEP8vV2EXeXxY+A+oUlnQ910rDPA7XArqDkGWCzcGxN7tp7qpdo/1I1n22yWgjeRMYulchyte+6eRuBUMKn8aU5mS0Sh/HMca3r5zJrpwsxPvu3+XfmwQyz6gB/LTLmQCG38PRAHLqh3tbeBnkHYffp7zp++hPMp7I6x05MJFIcUpUOjbrQZ/RzcIfa
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

